package jp.aquafactory.apprenticecodex.network;

import jp.aquafactory.apprenticecodex.network.packet.*;
import net.minecraft.network.protocol.common.custom.CustomPacketPayload;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.phys.Vec3;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.network.PacketDistributor;
import net.neoforged.neoforge.network.event.RegisterPayloadHandlersEvent;

public final class Networks {
    private static final String PROTOCOL_VERSION = "120";

    private Networks() {
    }

    public static void register(IEventBus modEventBus) {
        modEventBus.addListener(Networks::registerPayloads);
    }

    private static void registerPayloads(RegisterPayloadHandlersEvent event) {
        var registrar = event.registrar(PROTOCOL_VERSION);
        registrar.playToClient(LockOnRayTrailPacket.TYPE, LockOnRayTrailPacket.STREAM_CODEC, LockOnRayTrailPacket::handle);
        registrar.playToServer(ClientMalumBlackCrystalRevealedPacket.TYPE,
                ClientMalumBlackCrystalRevealedPacket.STREAM_CODEC, ClientMalumBlackCrystalRevealedPacket::handle);
        registrar.playToServer(ClientMantleDashInputPacket.TYPE, ClientMantleDashInputPacket.STREAM_CODEC, ClientMantleDashInputPacket::handle);
        registrar.playToClient(SyncMantleDashPacket.TYPE, SyncMantleDashPacket.STREAM_CODEC, SyncMantleDashPacket::handle);
        registrar.playToClient(SyncMantlePacket.TYPE, SyncMantlePacket.STREAM_CODEC, SyncMantlePacket::handle);
        registrar.playToServer(ClientMantleImpulsePacket.TYPE, ClientMantleImpulsePacket.STREAM_CODEC, ClientMantleImpulsePacket::handle);
        registrar.playToServer(ClientQuickBlinkInputPacket.TYPE, ClientQuickBlinkInputPacket.STREAM_CODEC, ClientQuickBlinkInputPacket::handle);
        registrar.playToClient(SyncQuickBlinkPacket.TYPE, SyncQuickBlinkPacket.STREAM_CODEC, SyncQuickBlinkPacket::handle);
        registrar.playToServer(ClientMantleFireworkInputPacket.TYPE, ClientMantleFireworkInputPacket.STREAM_CODEC,
                ClientMantleFireworkInputPacket::handle);
        registrar.playToClient(SyncFullautoEchoConfigPacket.TYPE,
                SyncFullautoEchoConfigPacket.STREAM_CODEC, SyncFullautoEchoConfigPacket::handle);
        registrar.playToServer(ClientMultipurposeStaffrifleAdsPacket.TYPE,
                ClientMultipurposeStaffrifleAdsPacket.STREAM_CODEC, ClientMultipurposeStaffrifleAdsPacket::handle);
        registrar.playToServer(ClientFullautoRapidcastSpellrifleAdsPacket.TYPE,
                ClientFullautoRapidcastSpellrifleAdsPacket.STREAM_CODEC, ClientFullautoRapidcastSpellrifleAdsPacket::handle);
        registrar.playToClient(SyncChargedTwinBladeStaffConfigPacket.TYPE,
                SyncChargedTwinBladeStaffConfigPacket.STREAM_CODEC, SyncChargedTwinBladeStaffConfigPacket::handle);
        registrar.playToClient(SyncChargedStaffRiptidePacket.TYPE,
                SyncChargedStaffRiptidePacket.STREAM_CODEC, SyncChargedStaffRiptidePacket::handle);
        registrar.playToClient(
                SyncQuickcastCartridgePacket.TYPE,
                SyncQuickcastCartridgePacket.STREAM_CODEC,
                SyncQuickcastCartridgePacket::handle);
        registrar.playToServer(
                ClientInterruptCartridgeReloadPacket.TYPE,
                ClientInterruptCartridgeReloadPacket.STREAM_CODEC,
                ClientInterruptCartridgeReloadPacket::handle);
        registrar.playToClient(SyncElementalBowCastPacket.TYPE,
                SyncElementalBowCastPacket.STREAM_CODEC,
                SyncElementalBowCastPacket::handle);
        registrar.playToServer(ClientElementalBowCancelPacket.TYPE,
                ClientElementalBowCancelPacket.STREAM_CODEC,
                ClientElementalBowCancelPacket::handle);
        registrar.playToClient(SupportedShieldPassagePacket.TYPE,
                SupportedShieldPassagePacket.STREAM_CODEC,
                SupportedShieldPassagePacket::handle);
        registrar.playToServer(ClientQuickcastCartridgePacket.TYPE,
                ClientQuickcastCartridgePacket.STREAM_CODEC,
                ClientQuickcastCartridgePacket::handle);
        registrar.playToClient(ScytheRecallEffectPacket.TYPE,
                ScytheRecallEffectPacket.STREAM_CODEC,
                ScytheRecallEffectPacket::handle);
        registrar.playToServer(
                ClientBlockTargetCastPacket.TYPE,
                ClientBlockTargetCastPacket.STREAM_CODEC,
                ClientBlockTargetCastPacket::handle
        );
        registrar.playToServer(
                ClientFocusStaffbowCancelPacket.TYPE,
                ClientFocusStaffbowCancelPacket.STREAM_CODEC,
                ClientFocusStaffbowCancelPacket::handle
        );
        registrar.playToClient(
                SyncFocusStaffbowConfigPacket.TYPE,
                SyncFocusStaffbowConfigPacket.STREAM_CODEC,
                SyncFocusStaffbowConfigPacket::handle
        );
        registrar.playToClient(
                SyncSpellReaperScytheConfigPacket.TYPE,
                SyncSpellReaperScytheConfigPacket.STREAM_CODEC,
                SyncSpellReaperScytheConfigPacket::handle
        );
        registrar.playToClient(
                SyncElementalBowConfigPacket.TYPE,
                SyncElementalBowConfigPacket.STREAM_CODEC,
                SyncElementalBowConfigPacket::handle
        );
        registrar.playToClient(
                SyncChargecastCatalystbookConfigPacket.TYPE,
                SyncChargecastCatalystbookConfigPacket.STREAM_CODEC,
                SyncChargecastCatalystbookConfigPacket::handle
        );
        registrar.playToServer(
                ClientConfirmElementalBowModePacket.TYPE,
                ClientConfirmElementalBowModePacket.STREAM_CODEC,
                ClientConfirmElementalBowModePacket::handle
        );
        registrar.playToServer(
                ClientConfirmLuminousDeviceSelectionPacket.TYPE,
                ClientConfirmLuminousDeviceSelectionPacket.STREAM_CODEC,
                ClientConfirmLuminousDeviceSelectionPacket::handle
        );
        registrar.playToServer(
                ClientConfirmSneakSelectionPacket.TYPE,
                ClientConfirmSneakSelectionPacket.STREAM_CODEC,
                ClientConfirmSneakSelectionPacket::handle
        );
        registrar.playToServer(
                ClientChangeArchivistsGrimoireRowPacket.TYPE,
                ClientChangeArchivistsGrimoireRowPacket.STREAM_CODEC,
                ClientChangeArchivistsGrimoireRowPacket::handle
        );
        registrar.playToServer(
                ClientOpenSpellcasterAccessoryCasePacket.TYPE,
                ClientOpenSpellcasterAccessoryCasePacket.STREAM_CODEC,
                ClientOpenSpellcasterAccessoryCasePacket::handle
        );
        registrar.playToServer(
                ClientOpenStorageStabilizerEnderChestPacket.TYPE,
                ClientOpenStorageStabilizerEnderChestPacket.STREAM_CODEC,
                ClientOpenStorageStabilizerEnderChestPacket::handle
        );
        registrar.playToServer(
                ClientConfigureSpellcasterAccessoryCaseMenuPacket.TYPE,
                ClientConfigureSpellcasterAccessoryCaseMenuPacket.STREAM_CODEC,
                ClientConfigureSpellcasterAccessoryCaseMenuPacket::handle
        );
        registrar.playToServer(
                ClientSwingMagicAttackPacket.TYPE,
                ClientSwingMagicAttackPacket.STREAM_CODEC,
                ClientSwingMagicAttackPacket::handle
        );
        registrar.playToServer(
                ClientEpicFightAttackcastRingTargetsPacket.TYPE,
                ClientEpicFightAttackcastRingTargetsPacket.STREAM_CODEC,
                ClientEpicFightAttackcastRingTargetsPacket::handle
        );
        registrar.playToServer(
                ClientMultipurposeStaffrifleCastPacket.TYPE,
                ClientMultipurposeStaffrifleCastPacket.STREAM_CODEC,
                ClientMultipurposeStaffrifleCastPacket::handle
        );
        registrar.playToServer(
                ClientFullautoRapidcastSpellrifleCastPacket.TYPE,
                ClientFullautoRapidcastSpellrifleCastPacket.STREAM_CODEC,
                ClientFullautoRapidcastSpellrifleCastPacket::handle
        );
        registrar.playToServer(
                ClientSpellgunCastPacket.TYPE,
                ClientSpellgunCastPacket.STREAM_CODEC,
                ClientSpellgunCastPacket::handle
        );
        registrar.playToServer(
                ClientManaThrusterInputPacket.TYPE,
                ClientManaThrusterInputPacket.STREAM_CODEC,
                ClientManaThrusterInputPacket::handle
        );
        registrar.playToServer(
                ClientBroomInputPacket.TYPE,
                ClientBroomInputPacket.STREAM_CODEC,
                ClientBroomInputPacket::handle
        );
        registrar.playToClient(
                HoverrideBroomReleaseResultPacket.TYPE,
                HoverrideBroomReleaseResultPacket.STREAM_CODEC,
                HoverrideBroomReleaseResultPacket::handle
        );
        registrar.playToClient(
                HoverrideBroomAssistWingsJumpPacket.TYPE,
                HoverrideBroomAssistWingsJumpPacket.STREAM_CODEC,
                HoverrideBroomAssistWingsJumpPacket::handle
        );
        registrar.playToClient(
                HoverrideBroomImpulseEffectPacket.TYPE,
                HoverrideBroomImpulseEffectPacket.STREAM_CODEC,
                HoverrideBroomImpulseEffectPacket::handle
        );
        registrar.playToServer(
                ClientBroomDismountInputPacket.TYPE,
                ClientBroomDismountInputPacket.STREAM_CODEC,
                ClientBroomDismountInputPacket::handle
        );
        registrar.playToServer(
                ClientJumpcastCharmCastPacket.TYPE,
                ClientJumpcastCharmCastPacket.STREAM_CODEC,
                ClientJumpcastCharmCastPacket::handle
        );
        registrar.playToServer(
                ClientManaManeuverGearJumpPacket.TYPE,
                ClientManaManeuverGearJumpPacket.STREAM_CODEC,
                ClientManaManeuverGearJumpPacket::handle
        );
        registrar.playToServer(
                ClientAnchorBlinkPacket.TYPE,
                ClientAnchorBlinkPacket.STREAM_CODEC,
                ClientAnchorBlinkPacket::handle
        );
        registrar.playToServer(
                ClientMirageAvoidanceCastPacket.TYPE,
                ClientMirageAvoidanceCastPacket.STREAM_CODEC,
                ClientMirageAvoidanceCastPacket::handle
        );
        registrar.playToClient(
                SyncEnderGrimoireSpellbookPacket.TYPE,
                SyncEnderGrimoireSpellbookPacket.STREAM_CODEC,
                SyncEnderGrimoireSpellbookPacket::handle
        );
        registrar.playToClient(
                SyncIsekaiTravelGuidebookConfigPacket.TYPE,
                SyncIsekaiTravelGuidebookConfigPacket.STREAM_CODEC,
                SyncIsekaiTravelGuidebookConfigPacket::handle
        );
        registrar.playToClient(
                SyncInstantSearchBrazierConfigPacket.TYPE,
                SyncInstantSearchBrazierConfigPacket.STREAM_CODEC,
                SyncInstantSearchBrazierConfigPacket::handle
        );
        registrar.playToClient(
                SyncApprenticeDeskConfigPacket.TYPE,
                SyncApprenticeDeskConfigPacket.STREAM_CODEC,
                SyncApprenticeDeskConfigPacket::handle
        );
        registrar.playToClient(
                SyncAssistWingsJumpPacket.TYPE,
                SyncAssistWingsJumpPacket.STREAM_CODEC,
                SyncAssistWingsJumpPacket::handle
        );
        registrar.playToClient(
                SyncManaManeuverGearJumpPacket.TYPE,
                SyncManaManeuverGearJumpPacket.STREAM_CODEC,
                SyncManaManeuverGearJumpPacket::handle
        );
        registrar.playToClient(
                SyncManaManeuverGearSlidePacket.TYPE,
                SyncManaManeuverGearSlidePacket.STREAM_CODEC,
                SyncManaManeuverGearSlidePacket::handle
        );
        registrar.playToClient(
                ManaManeuverGearFallEffectPacket.TYPE,
                ManaManeuverGearFallEffectPacket.STREAM_CODEC,
                ManaManeuverGearFallEffectPacket::handle
        );
        registrar.playToClient(
                SyncManaForceBladeConfigPacket.TYPE,
                SyncManaForceBladeConfigPacket.STREAM_CODEC,
                SyncManaForceBladeConfigPacket::handle
        );
        registrar.playToClient(
                SyncManaShieldCharmConfigPacket.TYPE,
                SyncManaShieldCharmConfigPacket.STREAM_CODEC,
                SyncManaShieldCharmConfigPacket::handle
        );
        registrar.playToClient(
                SyncManaSoulTransducerConfigPacket.TYPE,
                SyncManaSoulTransducerConfigPacket.STREAM_CODEC,
                SyncManaSoulTransducerConfigPacket::handle
        );
        registrar.playToClient(
                SyncUndyingEmblemConfigPacket.TYPE,
                SyncUndyingEmblemConfigPacket.STREAM_CODEC,
                SyncUndyingEmblemConfigPacket::handle
        );
        registrar.playToClient(
                SyncUndyingEmblemStatePacket.TYPE,
                SyncUndyingEmblemStatePacket.STREAM_CODEC,
                SyncUndyingEmblemStatePacket::handle
        );
        registrar.playToClient(
                SyncManaThrusterConfigPacket.TYPE,
                SyncManaThrusterConfigPacket.STREAM_CODEC,
                SyncManaThrusterConfigPacket::handle
        );
        registrar.playToClient(
                SyncFloatmountBroomConfigPacket.TYPE,
                SyncFloatmountBroomConfigPacket.STREAM_CODEC,
                SyncFloatmountBroomConfigPacket::handle
        );
        registrar.playToClient(
                SyncManaThrusterActivePacket.TYPE,
                SyncManaThrusterActivePacket.STREAM_CODEC,
                SyncManaThrusterActivePacket::handle
        );
        registrar.playToClient(
                SyncZenithStaffConfigPacket.TYPE,
                SyncZenithStaffConfigPacket.STREAM_CODEC,
                SyncZenithStaffConfigPacket::handle
        );
        registrar.playToClient(
                SyncEquipmentSpellTimingConfigPacket.TYPE,
                SyncEquipmentSpellTimingConfigPacket.STREAM_CODEC,
                SyncEquipmentSpellTimingConfigPacket::handle
        );
        registrar.playToClient(
                SyncLuminousDeviceConfigPacket.TYPE,
                SyncLuminousDeviceConfigPacket.STREAM_CODEC,
                SyncLuminousDeviceConfigPacket::handle
        );
        registrar.playToClient(
                SyncMageLightConfigPacket.TYPE,
                SyncMageLightConfigPacket.STREAM_CODEC,
                SyncMageLightConfigPacket::handle
        );
        registrar.playToClient(
                SyncLinearBuildConfigPacket.TYPE,
                SyncLinearBuildConfigPacket.STREAM_CODEC,
                SyncLinearBuildConfigPacket::handle
        );
        registrar.playToClient(
                SyncScarletThirstHealthPacket.TYPE,
                SyncScarletThirstHealthPacket.STREAM_CODEC,
                SyncScarletThirstHealthPacket::handle
        );
        registrar.playToClient(
                SyncSchoolAffinityAssignmentsPacket.TYPE,
                SyncSchoolAffinityAssignmentsPacket.STREAM_CODEC,
                SyncSchoolAffinityAssignmentsPacket::handle
        );
        registrar.playToClient(
                ForceFieldDefenseEffectPacket.TYPE,
                ForceFieldDefenseEffectPacket.STREAM_CODEC,
                ForceFieldDefenseEffectPacket::handle
        );
        registrar.playToClient(
                HealingBloomPulsePacket.TYPE,
                HealingBloomPulsePacket.STREAM_CODEC,
                HealingBloomPulsePacket::handle
        );
        registrar.playToClient(
                HeavenlyFistPulsePacket.TYPE,
                HeavenlyFistPulsePacket.STREAM_CODEC,
                HeavenlyFistPulsePacket::handle
        );
        registrar.playToClient(
                TotemOfPermafrostPulsePacket.TYPE,
                TotemOfPermafrostPulsePacket.STREAM_CODEC,
                TotemOfPermafrostPulsePacket::handle
        );
        registrar.playToClient(
                ManaSiphonOrbEffectPacket.TYPE,
                ManaSiphonOrbEffectPacket.STREAM_CODEC,
                ManaSiphonOrbEffectPacket::handle
        );
        registrar.playToClient(
                SyncRemoteEyeStatePacket.TYPE,
                SyncRemoteEyeStatePacket.STREAM_CODEC,
                SyncRemoteEyeStatePacket::handle
        );
        registrar.playToClient(
                SyncMirageAvoidanceStatePacket.TYPE,
                SyncMirageAvoidanceStatePacket.STREAM_CODEC,
                SyncMirageAvoidanceStatePacket::handle
        );
        registrar.playToClient(
                SyncElementalBowOverheatPacket.TYPE,
                SyncElementalBowOverheatPacket.STREAM_CODEC,
                SyncElementalBowOverheatPacket::handle
        );
        registrar.playToClient(
                SyncCircuitHeatStaffOverheatPacket.TYPE,
                SyncCircuitHeatStaffOverheatPacket.STREAM_CODEC,
                SyncCircuitHeatStaffOverheatPacket::handle
        );
        registrar.playToClient(
                SyncCircuitHeatStaffConfigPacket.TYPE,
                SyncCircuitHeatStaffConfigPacket.STREAM_CODEC,
                SyncCircuitHeatStaffConfigPacket::handle
        );
        registrar.playToClient(
                SyncIronSwingcastStaffConfigPacket.TYPE,
                SyncIronSwingcastStaffConfigPacket.STREAM_CODEC,
                SyncIronSwingcastStaffConfigPacket::handle
        );
        registrar.playToClient(
                SyncArcanumInAJarConfigPacket.TYPE,
                SyncArcanumInAJarConfigPacket.STREAM_CODEC,
                SyncArcanumInAJarConfigPacket::handle
        );
        registrar.playToClient(
                SyncHighTierSwingcastStaffConfigPacket.TYPE,
                SyncHighTierSwingcastStaffConfigPacket.STREAM_CODEC,
                SyncHighTierSwingcastStaffConfigPacket::handle
        );
        registrar.playToClient(
                SyncSoulstainedSteelSwingcastStaffConfigPacket.TYPE,
                SyncSoulstainedSteelSwingcastStaffConfigPacket.STREAM_CODEC,
                SyncSoulstainedSteelSwingcastStaffConfigPacket::handle
        );
        registrar.playToClient(
                SyncSpellgunConfigPacket.TYPE,
                SyncSpellgunConfigPacket.STREAM_CODEC,
                SyncSpellgunConfigPacket::handle
        );
        registrar.playToClient(
                SyncAutocastAmuletNotificationPacket.TYPE,
                SyncAutocastAmuletNotificationPacket.STREAM_CODEC,
                SyncAutocastAmuletNotificationPacket::handle
        );
        registrar.playToClient(
                SyncAutocastAmuletProfileSpellIdsPacket.TYPE,
                SyncAutocastAmuletProfileSpellIdsPacket.STREAM_CODEC,
                SyncAutocastAmuletProfileSpellIdsPacket::handle
        );
        registrar.playToClient(
                SyncEchoProfileSpellIdsPacket.TYPE,
                SyncEchoProfileSpellIdsPacket.STREAM_CODEC,
                SyncEchoProfileSpellIdsPacket::handle
        );
        registrar.playToClient(
                SyncRemainingCountNotificationPacket.TYPE,
                SyncRemainingCountNotificationPacket.STREAM_CODEC,
                SyncRemainingCountNotificationPacket::handle
        );
        registrar.playToClient(
                SyncFocusStaffbowCastStatePacket.TYPE,
                SyncFocusStaffbowCastStatePacket.STREAM_CODEC,
                SyncFocusStaffbowCastStatePacket::handle
        );
        registrar.playToClient(
                SyncFocusStaffbowLoanPacket.TYPE,
                SyncFocusStaffbowLoanPacket.STREAM_CODEC,
                SyncFocusStaffbowLoanPacket::handle
        );
        registrar.playToClient(
                SyncFocusStaffbowPresentationPacket.TYPE,
                SyncFocusStaffbowPresentationPacket.STREAM_CODEC,
                SyncFocusStaffbowPresentationPacket::handle
        );
        registrar.playToClient(
                SyncBoundBowStatePacket.TYPE,
                SyncBoundBowStatePacket.STREAM_CODEC,
                SyncBoundBowStatePacket::handle
        );
        registrar.playToClient(
                SyncBoundSwordStatePacket.TYPE,
                SyncBoundSwordStatePacket.STREAM_CODEC,
                SyncBoundSwordStatePacket::handle
        );
        registrar.playToClient(
                SyncEdgeDancerStatePacket.TYPE,
                SyncEdgeDancerStatePacket.STREAM_CODEC,
                SyncEdgeDancerStatePacket::handle
        );
        registrar.playToClient(
                SyncTamersPocketCountPacket.TYPE,
                SyncTamersPocketCountPacket.STREAM_CODEC,
                SyncTamersPocketCountPacket::handle
        );
        registrar.playToClient(
                SyncPhotonSiphonCombatStatePacket.TYPE,
                SyncPhotonSiphonCombatStatePacket.STREAM_CODEC,
                SyncPhotonSiphonCombatStatePacket::handle
        );
        registrar.playToClient(
                SpellrifleMuzzleParticlePacket.TYPE,
                SpellrifleMuzzleParticlePacket.STREAM_CODEC,
                SpellrifleMuzzleParticlePacket::handle
        );
        registrar.playToClient(
                SyncMultipurposeStaffrifleFireEffectPacket.TYPE,
                SyncMultipurposeStaffrifleFireEffectPacket.STREAM_CODEC,
                SyncMultipurposeStaffrifleFireEffectPacket::handle
        );
        registrar.playToClient(
                SyncFullautoRapidcastSpellrifleFireEffectPacket.TYPE,
                SyncFullautoRapidcastSpellrifleFireEffectPacket.STREAM_CODEC,
                SyncFullautoRapidcastSpellrifleFireEffectPacket::handle
        );
        registrar.playToClient(
                SyncSmashcastScepterReadyStatePacket.TYPE,
                SyncSmashcastScepterReadyStatePacket.STREAM_CODEC,
                SyncSmashcastScepterReadyStatePacket::handle
        );
        registrar.playToClient(
                SyncSatelliteFollowcastAmuletStatePacket.TYPE,
                SyncSatelliteFollowcastAmuletStatePacket.STREAM_CODEC,
                SyncSatelliteFollowcastAmuletStatePacket::handle
        );
        registrar.playToClient(
                SenseEvilHighlightsPacket.TYPE,
                SenseEvilHighlightsPacket.STREAM_CODEC,
                SenseEvilHighlightsPacket::handle
        );
        registrar.playToClient(
                AtelierStationFluidEffectPacket.TYPE,
                AtelierStationFluidEffectPacket.STREAM_CODEC,
                AtelierStationFluidEffectPacket::handle
        );
        registrar.playToClient(
                AlchemyBrewerWaterSupplyEffectPacket.TYPE,
                AlchemyBrewerWaterSupplyEffectPacket.STREAM_CODEC,
                AlchemyBrewerWaterSupplyEffectPacket::handle
        );
        registrar.playToClient(
                SyncReflectcastShieldEffectPacket.TYPE,
                SyncReflectcastShieldEffectPacket.STREAM_CODEC,
                SyncReflectcastShieldEffectPacket::handle
        );
        registrar.playToClient(
                TerraResonancePulsePacket.TYPE,
                TerraResonancePulsePacket.STREAM_CODEC,
                TerraResonancePulsePacket::handle
        );
        registrar.playToClient(
                TerraResonanceHighlightsPacket.TYPE,
                TerraResonanceHighlightsPacket.STREAM_CODEC,
                TerraResonanceHighlightsPacket::handle
        );
        registrar.playToClient(
                DeepSensorObservationsPacket.TYPE,
                DeepSensorObservationsPacket.STREAM_CODEC,
                DeepSensorObservationsPacket::handle
        );
        registrar.playToClient(
                GunSpellTracerPacket.TYPE,
                GunSpellTracerPacket.STREAM_CODEC,
                GunSpellTracerPacket::handle
        );
        registrar.playToClient(
                LightningArrowImpactPacket.TYPE,
                LightningArrowImpactPacket.STREAM_CODEC,
                LightningArrowImpactPacket::handle
        );
    }

    public static void sendToPlayer(ServerPlayer serverPlayer, CustomPacketPayload packet) {
        PacketDistributor.sendToPlayer(serverPlayer, packet);
    }

    public static void sendToTrackingEntityAndSelf(Entity entity, CustomPacketPayload packet) {
        PacketDistributor.sendToPlayersTrackingEntityAndSelf(entity, packet);
    }

    public static void sendToServer(CustomPacketPayload packet) {
        PacketDistributor.sendToServer(packet);
    }

    public static void sendToPlayersNear(ServerLevel level, Vec3 center, double radius, CustomPacketPayload packet) {
        var radiusSqr = radius * radius;
        for (var player : level.players()) {
            if (player.distanceToSqr(center) <= radiusSqr) {
                sendToPlayer(player, packet);
            }
        }
    }
}
