modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="${mod_issue_tracker_url}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
displayURL="${mod_display_url}"
logoFile="${mod_logo_file}"
description='''${mod_description}'''

[[mixins]]
config="mixins.apprenticecodex.json"

[[dependencies.apprenticecodex]]
    modId="neoforge"
    mandatory=true
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.apprenticecodex]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.apprenticecodex]]
    modId="irons_spellbooks"
    mandatory=true
    versionRange="[${irons_spells_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.apprenticecodex]]
    modId="geckolib"
    mandatory=true
    versionRange="[${geckolib_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.apprenticecodex]]
    modId="curios"
    mandatory=true
    versionRange="[${curios_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="create"
    type="optional"
    versionRange="[${create_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="jade"
    type="optional"
    versionRange="[${jade_version},)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="lodestone"
    type="optional"
    versionRange="[${lodestone_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="malum"
    type="optional"
    versionRange="[${malum_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="jei"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="patchouli"
    type="optional"
    versionRange="[${patchouli_version},)"
    ordering="AFTER"
    side="BOTH"
